### ISSUE TITLE
Implement testing for multiclass eval

### ISSUE THREAD

**Issue by nrweir** [CosmiQ/solaris#11]
@nrweir commented on [Fri Dec 14 2018](https://github.com/CosmiQ/cw-eval/issues/24)

In #9 I didn't implement testing for multiclass eval because I didn't have appropriate data. We'd need to do the following:
- [ ] add multiclass ground truth and prediction data to cw_eval/data
- [ ] implement multiclass testing in tests/baseeval_test.py
- [ ] ensure the test suite runs OK through Travis

**Comment by jshermeyer** [comment]
Multiclass eval now possible via the eval/vector module.
