### ISSUE TITLE
Fix graph_to_geojson() in  vector/graph.py

### ISSUE THREAD

**Issue by avanetten** [CosmiQ/solaris#110]
Currently get an error trying to create the nodes geojson.  Need to set index as nodes (see osmnx)

    # create a GeoDataFrame of the nodes and set CRS
    nodes, data = zip(*G_save.nodes(data=True))
    gdf_nodes = gpd.GeoDataFrame(list(data), index=nodes)
    gdf_nodes.crs = G_save.graph['crs']
    # create a geometry column then drop the x and y columns
    gdf_nodes['geometry'] = gdf_nodes.apply(lambda row: Point(row['x'], row['y']), axis=1)

# Prerequisites
_Please answer the following questions for yourself before submitting an issue._
- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Instructions
_Please complete the following sections of the issue template, removing irrelevant components._

---

# Bug Report
_Remove this section if your issue is not a bug. Make sure to add the __Type: Bug__ label if it is._

## Failure Information
_Please help provide information about the failure._

## Bug Report: Expected Behavior
_(Expected behavior that isn't occurring)_

## Bug Report: Current Behavior
_(Description of the current, buggy behavior)_

## Bug Report: Steps to Reproduce
_Please provide detailed steps for reproducing the issue._
1. Step 1
2. Step 2
3. Etc.

## Bug Report: Context
_Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions._
- OS:
- Python version:
- `solaris` install method (Conda, pip, Docker):
- `solaris` version (release vs. dev) - if you're using an older release, please update and ensure your issue isn't resolved:
- Additional relevant environment details (e.g. using a virtual environment or not, version of GDAL and GDAL install method, etc.)

## Bug Report: Failure Logs
_Please include any relevant log snippets, python shell commands and tracebacks, etc. here._

---

# Feature Request
_Remove this section if your issue is not a feature request. Make sure to add the __Type: Enhancement__ label if it is._
## Feature Description
_Please describe the feature you'd like implemented._

## Feature Request: Changes to API
_If your feature request includes changes to the `solaris` API, describe that here. Note that any changes to required arguments or argument order in the API will only be made at a major version release. See [the contributing guidelines]() for additional details._

---

# Final steps

## References to other issues/PRs
_If you did not already include references above, list references to relevant PRs, issues, or other pages here._

## Labels
_Make sure to select a __Type__ label for your issue. The repo maintainers will add other labels, milestones, and projects (if applicable)._

**Comment by nrweir** [comment]
Can you paste the error output here?

**Comment by avanetten** [comment]
...: outpath_json = os.path.join(outdir, 'AOI_2_Vegas_img50_btw.geojson') 
   ...: sol.vector.graph.graph_to_geojson(G, outpath_json, encoding='utf-8', overwrite=False) 
   ...:                                                                                                                
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

TypeError: an integer is required

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-9-b9fa879d2a81> in <module>
      1 # fails
      2 outpath_json = os.path.join(outdir, 'AOI_2_Vegas_img50_btw.geojson')
----> 3 sol.vector.graph.graph_to_geojson(G, outpath_json, encoding='utf-8', overwrite=False)

/anaconda3/envs/apls/lib/python3.6/site-packages/solaris/vector/graph.py in graph_to_geojson(G, output_path, encoding, overwrite)
    488     gdf_nodes.crs = G_to_save.graph['crs']
    489     gdf_nodes['geometry'] = gdf_nodes.apply(
--> 490         lambda row: Point(row['x'], row['y']), axis=1
    491         )
    492     gdf_nodes = gdf_nodes.drop(columns=['x', 'y'])

/anaconda3/envs/apls/lib/python3.6/site-packages/pandas/core/frame.py in apply(self, func, axis, broadcast, raw, reduce, result_type, args, **kwds)
   6012                          args=args,
   6013                          kwds=kwds)
-> 6014         return op.get_result()
   6015 
   6016     def applymap(self, func):

/anaconda3/envs/apls/lib/python3.6/site-packages/pandas/core/apply.py in get_result(self)
    140             return self.apply_raw()
    141 
--> 142         return self.apply_standard()
    143 
    144     def apply_empty_result(self):

/anaconda3/envs/apls/lib/python3.6/site-packages/pandas/core/apply.py in apply_standard(self)
    246 
    247         # compute the result using the series generator
--> 248         self.apply_series_generator()
    249 
    250         # wrap results

/anaconda3/envs/apls/lib/python3.6/site-packages/pandas/core/apply.py in apply_series_generator(self)
    275             try:
    276                 for i, v in enumerate(series_gen):
--> 277                     results[i] = self.f(v)
    278                     keys.append(v.name)
    279             except Exception as e:

/anaconda3/envs/apls/lib/python3.6/site-packages/solaris/vector/graph.py in <lambda>(row)
    488     gdf_nodes.crs = G_to_save.graph['crs']
    489     gdf_nodes['geometry'] = gdf_nodes.apply(
--> 490         lambda row: Point(row['x'], row['y']), axis=1
    491         )
    492     gdf_nodes = gdf_nodes.drop(columns=['x', 'y'])

/anaconda3/envs/apls/lib/python3.6/site-packages/pandas/core/series.py in __getitem__(self, key)
    765         key = com._apply_if_callable(key, self)
    766         try:
--> 767             result = self.index.get_value(self, key)
    768 
    769             if not is_scalar(result):

/anaconda3/envs/apls/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_value(self, series, key)
   3116         try:
   3117             return self._engine.get_value(s, k,
-> 3118                                           tz=getattr(series.dtype, 'tz', None))
   3119         except KeyError as e1:
   3120             if len(self) > 0 and self.inferred_type in ['integer', 'boolean']:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

KeyError: ('x', 'occurred at index bridge_type')
