### ISSUE TITLE
Enable creation of bounding boxes from polygons

### ISSUE THREAD

**Issue by nrweir** [CosmiQ/solaris#12]
@nrweir commented on [Wed Apr 17 2019](https://github.com/CosmiQ/cw-geodata/issues/48)

@avanetten, I think you/we might have code to do this already for a variety of formats (TFRecord, COCO, Darknet) - can we try to port this in?

**Comment by jshermeyer** [comment]
I think this one could be multiple issues.  I can help with some of these but not all.

**Comment by nrweir** [comment]
Yeah I think some of them are already listed as parts of other issues (see #14). If there's one missing feel free to create another issue. You can also mark that other issue as a dependency for this one (if you feel like it).
