### ISSUE TITLE
[Return GDFs during eval]: (Return gdfs for TP, FN, FP when running eval)

### ISSUE THREAD

**Issue by jshermeyer** [CosmiQ/solaris#138]
**Is your feature request related to a problem? Please describe.**
Would like to add functionality to return gdfs for TP, FN, FP when running eval for retraining a model after its first iteration, and this is a prereq for fine grain classification with different classifiers.

**Describe the solution you'd like**
Wrote a function to do this

**Describe alternatives you've considered**
No

**Additional context**
np.nan

**Comment by nrweir** [comment]
If possible to do this within the context of the EvalBase object as it's structured now that'd be awesome; if that doesn't make sense given the use case (I'm not quite following the description) no worries.

**Comment by jshermeyer** [comment]
Yeah it's in the EvalBase object.  Identical to eval_iou just returns 3 GDFs  also that can be converted to geojsons for visualization.
