### ISSUE TITLE
split_multi_geometries not applied

### ISSUE THREAD

**Issue by chrieke** [CosmiQ/solaris#187]
Great project, started digging around a bit. Sorry for not using the issue templates.

1. In both dev and master branch, in [tile/vector_tile/tile_generator](https://github.com/CosmiQ/solaris/blob/dev/solaris/tile/vector_tile.py#L87)  the [split_multi_geometries function](https://github.com/CosmiQ/solaris/blob/38ec54035c0dc37c2e256353e5f32cde3b6c034c/solaris/utils/geo.py#L489) doesn't seem to be applied to the geodataframe yet? Currently the vector tiling step in the tiling_tutorial fails for some chips (GeometryTypeValidationError when writing out the dataframe because there are both Polygons and Multipolygons in it).

2. In [core/_check_gdf_load ](https://github.com/CosmiQ/solaris/blob/f2fe193c5d5417f58186e167fde80f8f69176b3f/solaris/utils/core.py#L54) an empty geodataframe is returned if reading from the json file fails. That way, if the filepath is actually wrong the user gets a crs error further down the trace, which is confusing. Would add a CPLE_OpenFailedError warning or maybe you don't need the empty gdf alltogether. 

3. In the documentation, would prefer the configuration of the left menu bar a bit more as in e.g. the rasterio documentation, more sub-chapters showing. Right now its a bit difficult to navigate.

**Comment by nrweir** [comment]
Hey @chrieke, thanks for checking it out and adding these thoughts, I appreciate it! I'll get to work on them.

**Comment by nrweir** [comment]
Resolved with #189. Creating a new issue to track your third point for when I get around to working on the docs.
