### ISSUE TITLE
[BUG]: Problems with multi-channel mask creation when meters=True and no polys in contact_mask

### ISSUE THREAD

**Issue by nrweir** [CosmiQ/solaris#205]
From @daveluo: This throws an error on the Zanzibar data.

```
# TODO: investigate bug w/ meters=True and contact_mask is_valid_geom() failing when there's no intersecting poly

 fbc_mask = sol.vector.mask.df_to_px_mask(df=polys_gdf,
                                          channels=['footprint', 'boundary', 'contact'],
                                          affine_obj=tfm, shape=(size,size),
                                          boundary_width=5, boundary_type='inner', contact_spacing=10, meters=False)

```

**Comment by daveluo** [comment]
Thanks @nrweir for posting this. I think I found the issue which is w/ my data source: there were a bunch of hard-to-spot invalid and duplicate overlapping geometries in the original zanzibar geojson file. Once I ran it through .buffer(0) and cascaded_union+explode operations to preemptively clean up the geoms, contact_mask worked perfectly. Sorry for the false alarm. I think this can be closed!

**Comment by nrweir** [comment]
Good to know. Thanks @daveluo !
