### ISSUE TITLE
[FEATURE]: How do I train a model?

### ISSUE THREAD

**Issue by Zumbalamambo** [CosmiQ/solaris#208]
**Is your feature request related to a problem? Please describe.**
How do I train a model for the object detection or segmentation? The documentation seems to be quite vague. Adding a research folder as in tensorflow or any examples to train/test the models would of a great value

**Comment by nrweir** [comment]
Hi @zumbalamambo,

I'm out of office this week but will respond next week if you still need help. The tutorials in the documentation - specifically the .yaml config tutorial and the training tutorial in the API section - may help. If not, if you can provide a specific set of questions related to training I can try to improve the clarity of the docs. 

There currently isn't functionality implemented for object detection model training.
