### ISSUE TITLE
[BUG]: TorchModelCheckPoint weights_only error

### ISSUE THREAD

**Issue by bruesba** [CosmiQ/solaris#218]
Hi,

Training a model with `model_checkpoint` enabled leads to the following error after the first epoch:
> TypeError: save() missing 1 required positional argument: 'weights_only'

My linter highlights the following problem several times from line 181 of torch_callbacks.py:
> No value for argument 'weights_only' in method call

Seems easy enough to squash but I'm not sure where to start .

Best,

**Comment by nrweir** [comment]
Hi @bruesba,

Can you past the whole traceback for the TypeError here, including the line in training that throws the error?

Thanks

**Comment by nrweir** [comment]
I _think_ this is something that we've fixed in the dev branch (#20, we just haven't merged it into master for the 0.1.3 release. In the meantime, you could try installing solaris from the dev branch on github and see if it resolves the problem.

**Comment by bruesba** [comment]
Hi Nick,

The dev installation leads to the same error:
> Traceback (most recent call last):
  File "c:/Users/blue/Documents/solaris-dev/solaris/train.py", line 5, in <module>
    trainer.train()
  File "c:\Users\blue\Documents\solaris-dev\solaris\solaris\nets\train.py", line 167, in train
    val_loss.detach().cpu().numpy())
  File "c:\Users\blue\Documents\solaris-dev\solaris\solaris\nets\train.py", line 196, in _run_torch_callbacks
    cb(self.model, loss_value=val_loss)
  File "c:\Users\blue\Documents\solaris-dev\solaris\solaris\nets\torch_callbacks.py", line 188, in __call__
    self.save(model)
TypeError: save() missing 1 required positional argument: 'weights_only'

Best

**Comment by bruesba** [comment]
Changing `self.save(model)` to `self.save(model, self.weights_only)` on lines 181, 188, 193 and 200 of torch_callbacks.py seems to solve the issue - the model no longer crashes at the end of the first epoch. 

I was also wondering how training can be resumed when checkpointing is enabled. In the default .yml configuration files, checkpoints are saved to 'xdxd_best.pth'. How does one configure on what weights a model is trained? https://solaris.readthedocs.io/en/latest/tutorials/notebooks/creating_the_yaml_config_file.html specifies how the input model and output weights can be set, but I can't find how to direct to input weights.

Best,
Blue

**Comment by bruesba** [comment]
I found another one. After the final epoch of training, Python thows
>Traceback (most recent call last):
  File "c:/Users/blue/Documents/solaris/xdxd_training.py", line 5, in <module>
    trainer.train()
  File "c:\Users\blue\Documents\solaris\solaris\nets\train.py", line 171, in train
    self.save_model()
  File "c:\Users\blue\Documents\solaris\solaris\nets\train.py", line 207, in save_model
    if isinstance(self.model, nn.DataParallel):
NameError: name 'nn' is not defined

Changing line 207 of train.py from `if isinstance(self.model, nn.DataParallel):` to `if isinstance(self.model, torch.nn.DataParallel):` allows training to conclude properly.

Best,
Blue

**Comment by nrweir** [comment]
Alright thanks for catching those, they'll get fixed for 0.1.3.

**Comment by nrweir** [comment]
For resuming training: I believe if you set `pretrained: true` and `model_path: [path_to_your_weights_file]`, that _should_ load in those weights and continue training from there. If that doesn't work let me know.

**Comment by bruesba** [comment]
Clear! Cheers

**Comment by nrweir** [comment]
Probably leave it open until a PR fixes it (which I'm actually about to merge in right now, I'll close it when I do)

**Comment by nrweir** [comment]
Resolved with #232.
