### ISSUE TITLE
[MAINT] links are broken for tutorial at https://solaris.readthedocs.io/en/latest/tutorials/notebooks/api_tiling_tutorial.html

### ISSUE THREAD

**Issue by khavernathy** [CosmiQ/solaris#279]
## Maintenance request summary

Please fix broken links for tutorial at https://solaris.readthedocs.io/en/latest/tutorials/notebooks/api_tiling_tutorial.html

Referring specifically to these:
Imagery: https://s3.amazonaws.com/spacenet-dataset/AOI_1_Rio/srcData/rasterData/3-Band.tar.gz

Vector labels: https://s3.amazonaws.com/spacenet-dataset/AOI_1_Rio/vectorData/Rio_BuildingLabels.tar.gz

**Comment by nrweir** [comment]
Thank you, good catch - those files were just moved yesterday.

**Comment by nrweir** [comment]
This is resolved now. If it's still showing the wrong paths, try clearing your cache.

**Comment by khavernathy** [comment]
Perfect, thanks!

**Comment by khavernathy** [comment]
Ah, looks like the sample data is a little different than the tutorial description.

e.g. I can't find 013022223133.tif anywhere, and the directory name is now `3band`, not `3-band`

..so I can't follow the example as-is

**Comment by nrweir** [comment]
I edited this and confirmed that it runs with the new filepaths.
