### ISSUE TITLE
[BUG]: environment.yml missing the requests package

### ISSUE THREAD

**Issue by yangsiyu007** [CosmiQ/solaris#299]
## Summary of the bug
`nets/model_io.py` uses the `requests` package, which is not in the `environment.yml` files.

## Steps to reproduce the bug
1. Clone the repo and install per instruction on the main readme:
```
conda env create -n solaris -f environment.yml
```
2. Add the location of the repo to PYTHONPTH
3. After that, importing `solaris` from another script will fail, complaining that `requests` is missing.

## Buggy behavior and/or error message
Importing `solaris` from another script fails. 

## Expected behavior
Being able to import `solaris` after installing it.

## Environment information
- OS:
- `solaris` version: 0.1.3

**Comment by rbavery** [comment]
Hi @yangsiyu007 ! I ran into this as well, I'll add the dependency in my PR.

**Comment by nrweir** [comment]
Hi @rbavery - It’s fixed in #300 already. Thanks!!

**Comment by yangsiyu007** [comment]
Hi @rbavery ! Good to see you here
