### ISSUE TITLE
[BUG]: aoi_bounds does not accept list like or shapely Polygons and only supports bounding boxes

### ISSUE THREAD

**Issue by rbavery** [CosmiQ/solaris#310]
## Summary of the bug
The [docs ](https://solaris.readthedocs.io/en/latest/api/tile.html#solaris.tile.raster_tile.RasterTiler.aoi_bounds) state that the a `aoi_bounds` arg to the tilers support shapely polygon and list like types, but supplying either of these throws an error, indicating that this arg was meant for a different bounds object, `rasterio.coords.BoundingBox`

```
AttributeError: 'Polygon' object has no attribute 'right'
```

## Expected behavior
Ideally one could supply not just a bounding box in either list, Polygon, or rasterio.coords.BoundingBox format but also polygons besides bounding boxes, since most vector labels are created within arbitrary polygon bounds (for example, state boundaries), instead of bounding boxes.

I'm working on a PR for this, updates to come!

**Comment by rbavery** [comment]
I'm thinking that this would do the trick: https://gist.github.com/lossyrob/7b620e6d2193cb55fbd0bffacf27f7f2

With some catches to make sure list-likes are handled correctly.

**Comment by nrweir** [comment]
@rbavery thanks for working on this, agree that including arbitrarily shaped bounds for tilers would be great!

**Comment by nrweir** [comment]
Resolved with #311!
