### ISSUE TITLE
[BUG]: Georegistering the dataframe into longitude, latitude coordinates

### ISSUE THREAD

**Issue by ishaankochhar** [CosmiQ/solaris#317]
_Thank you for helping us improve `solaris`!_

## Georegistering the dataframe into longitude, latitude coordinates
result_polys = sol.vector.polygon.georegister_px_df(mask2poly, 
                                                   affine_obj=tile_tfm, 
                                                   crs= 'epsg:4326')
type(result_polys)
geopandas.geodataframe.GeoDataFrame

```
sol.utils.geo.gdf_get_projection_unit(result_polys)
```

## Buggy behavior and/or error message
ValueError                                Traceback (most recent call last)
<ipython-input-151-55ff1c6de4ee> in <module>
----> 1 sol.utils.geo.gdf_get_projection_unit(result_polys)

~\Anaconda3\envs\solaris\lib\site-packages\solaris\utils\geo.py in gdf_get_projection_unit(vector_file)
    343     """
    344     c = _check_gdf_load(vector_file)
--> 345     crs = _check_crs(c.crs)
    346     srs = osr.SpatialReference()
    347     srs.ImportFromEPSG(crs.to_epsg())

~\Anaconda3\envs\solaris\lib\site-packages\solaris\utils\core.py in _check_crs(input_crs)
     91     elif isinstance(input_crs, str):
     92         # handle PROJ4 strings, epsg strings, wkt strings
---> 93         out_crs = rasterio.crs.CRS.from_string(input_crs)
     94     elif isinstance(input_crs, rasterio.crs.CRS):
     95         out_crs = input_crs

~\Anaconda3\envs\solaris\lib\site-packages\rasterio\crs.py in from_string(cls, string, morph_from_esri_dialect)
    343 
    344         elif string.strip().upper().startswith('EPSG:'):
--> 345             auth, val = string.strip().split(':')
    346             if not val:
    347                 raise CRSError("Invalid CRS: {!r}".format(string))

ValueError: too many values to unpack (expected 2)
```

```

## Expected behavior
It should display units of the coordinate reference systems. The unit i.e. meter, metre, or degree, of the projection.

## Environment information
- OS: Windows 10
- `solaris` version: 0.2.0
- python version: 3.6.7
- pyproj version: 2.4.2.post1
- fiona version: 1.8.13

**Comment by nrweir** [comment]
@ishaankochhar thanks for porting this over from SE. (For those interested, this originated [here](https://gis.stackexchange.com/questions/346232/crs-error-working-with-solaris).)

As I dug into this I found some issues with how the new implementation of `sol.utils.core._check_crs` handles strings. See the examples below:

```python
>>> import rasterio, os, pandas as pd, solaris as sol
>>> im = rasterio.open(os.path.join(sol.data.data_dir, 'sample_geotiff.tif'))
>>> fp_mask = pd.read_csv(os.path.join(sol.data.data_dir, 'sample_preds.csv'))
>>> result_polys = sol.vector.polygon.georegister_px_df(fp_mask, affine_obj=im.transform, crs='epsg:4326', geom_col='PolygonWKT_Pix')
>>> print(result_polys.crs)

'epsg:EPSG:4326'
```
or, replacing the last command and just passing the EPSG code as a string (without the `"EPSG:"` before it)

```python
>>> result_polys = sol.vector.polygon.georegister_px_df(fp_mask, affine_obj=im.transform, crs='4326', geom_col='PolygonWKT_Pix')

Traceback (most recent call last):
  File "rasterio/_crs.pyx", line 287, in rasterio._crs._CRS.from_wkt
  File "rasterio/_err.pyx", line 194, in rasterio._err.exc_wrap_ogrerr
rasterio._err.CPLE_BaseError: OGR Error code 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nweir/code/cosmiq_repos/solaris/solaris/vector/polygon.py", line 181, in georegister_px_df
    crs = _check_crs(crs)
  File "/Users/nweir/code/cosmiq_repos/solaris/solaris/utils/core.py", line 93, in _check_crs
    out_crs = rasterio.crs.CRS.from_string(input_crs)
  File "/opt/miniconda3/envs/solaris_debug/lib/python3.6/site-packages/rasterio/crs.py", line 349, in from_string
    return cls.from_wkt(string, morph_from_esri_dialect=morph_from_esri_dialect)
  File "/opt/miniconda3/envs/solaris_debug/lib/python3.6/site-packages/rasterio/crs.py", line 407, in from_wkt
    obj._crs = _CRS.from_wkt(wkt, morph_from_esri_dialect=morph_from_esri_dialect)
  File "rasterio/_crs.pyx", line 291, in rasterio._crs._CRS.from_wkt
rasterio.errors.CRSError: The WKT could not be parsed. OGR Error code 5
```

I'll try to figure out the best way to handle this. With #294 we changed how we handled strings to enable usage of CRSs that don't have EPSG codes, but it looks like we lost some support for EPSG ints passed as strings or strings like `'epsg:4326'`, etc.

**Comment by nrweir** [comment]
Digging around in `geopandas` issues and PRs, it looks like they're working on transitioning to using `pyproj.CRS` instances for tracking CRS. Given that most of `solaris` is built around `rasterio` I'm more inclined to stick with the implementation we moved to with #294.

However, I think we probably need to systematically update how CRSs are passed into `geopandas.GeoDataFrame`s to avoid the issues that we're encountering here.  My inclination is to pass the WKT string any time a CRS is being passed into a GeoDataFrame, e.g.:
```python
import geopandas as gpd
import rasterio

crs = rasterio.crs.CRS.from_epsg(4326)
gdf = gpd.GeoDataFrame({'geometry': [geoms]}, crs=crs.to_wkt())
```

I've checked to see if geopandas can parse CRSs represented as WKT strings (as it's supposed to be able to) and re-project using `gdf.to_crs()` when the CRS is provided in a different format (e.g. `gdf = gdf.to_crs('epsg:3395')`) and it all looks good. I'll check to make sure it behaves appropriately in the use cases listed above when I go through and make those changes.

@rbavery, any thoughts on this given that you did a lot of the work on CRSs?

**Comment by nrweir** [comment]
Issues weren't _entirely_ resolved with #319, now done with #322. will be releasing 0.2.1 now.

**Comment by ishaankochhar** [comment]
@nrweir expected release date of 0.2.1?

**Comment by nrweir** [comment]
@ishaankochhar now! :)
