### ISSUE TITLE
[BUG]: reorder axes in utlis of raster

### ISSUE THREAD

**Issue by sayakgis** [CosmiQ/solaris#318]
line 34 of solaris/solaris/utils/raster.py returns a Boolean, which seems to be incorrect, the current code is:
     elif len(axes == 4):
it should be **elif len(axes) == 4:**

**Comment by nrweir** [comment]
Great catch @sayakgis! If you want to make the change feel free to submit a PR; otherwise, we'll get to it before we release 0.2.1.

**Comment by nrweir** [comment]
This is fixed in #319.
