### ISSUE TITLE
It requires pytorch=1.3 when installed. However, pytorch 1.3 is now unavailable

### ISSUE THREAD

**Issue by Fayliu** [CosmiQ/solaris#337]
It requires pytorch=1.3 when installed. However, pytorch 1.3 is now unavailable on the website https://pytorch.org/get-started/locally/. How to deal with this problem? Many thanks for your help.

**Comment by nrweir** [comment]
Hi @Fayliu,

Torch 1.3 is still available, just not through that download link. If you don't have it installed, `pip` should install it for you during the `solaris` install process. That said, we're in the process of loosening up a lot of our version restrictions for this project, and will be accommodating `torch>1.3` soon.
