### ISSUE TITLE
[BUG]: environment-gpu.yml can't create environments

### ISSUE THREAD

**Issue by aghand0ur** [CosmiQ/solaris#338]
## Summary of the bug
Hi @nrweir,
Failed to install solaris on my machine with Titan Xp GPU.

## Steps to reproduce the bug
Please either paste sample code used to generate the buggy behavior below, or provide step-by-step instructions to reproduce the problem.

```
git clone https://github.com/cosmiq/solaris.git
cd solaris
conda env create -n solaris -f environment-gpu.yml
```

## Buggy behavior and/or error message
Please describe the buggy behavior and/or paste output here.
```
Package opencv conflicts for:
albumentations=0.4.3 -> opencv
opencv[version='>=4.1']The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2
```

## Environment information
- OS: Ubuntu 18.04

**Comment by nrweir** [comment]
Hi @aghand0ur, this doesn't seem to be a problem with solaris itself but with getting dependencies installed - specifically CUDA. Everything below assumes you have an NVIDIA GPU for deep learning - if not, disregard it.

As indicated in the traceback, there are issues with the CUDA/NVIDIA driver and the CUDA version you're trying to install. Check [your NVIDIA driver version and its CUDA compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html). If this isn't it, you can try installing different CUDA and/or torch versions in the environment-gpu.yml file.

I'm going to close the issue as it's not directly related to problems with `solaris` itself. Good luck.

-N

**Comment by aghand0ur** [comment]
Hi @nrweir,

As mentioned in my previous post, the machine is equipped with Titan Xp GPU.

According to the traceback, It seems that the CUDA version is incompatible with the opencv version. I am currently experimenting with different CUDA/opencv combinations.
N
Ali
