### ISSUE TITLE
[BUG]: Fiona/GeoPandas/Solaris import error

### ISSUE THREAD

**Issue by dphogan** [CosmiQ/solaris#343]
## Summary of the bug

When running Solaris in a container built from a Docker image generated with Solaris's Dockerfile, importing Fiona fails with an error message.  This affects anything that depends on Fiona, including GeoPandas and Solaris itself.

## Steps to reproduce the bug

1. Build a Docker image from docker/gpu/Dockerfile.
2. Run a container with the image.
3. Type "python"
4. Type "import fiona"

## Buggy behavior and/or error message

>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/fiona/__init__.py", line 84, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libnetcdf.so.15: cannot open shared object file: No such file or directory

*The same error is generated by "import geopandas" and "import solaris".
*Errors like this are often related to various libraries being pulled from different channels, but I don't know what the cause is in this specific case.

## Expected behavior

These libraries should load without error.

## Environment information
- OS:
- `solaris` version: current master as well as current dev
- python version: 3.7.6
- version of any relevant dependencies (optional - we may ask for this information later if not provided): fiona 1.8.13

**Comment by opee007** [comment]
hi! I encountered the same error, did you solve it?

**Comment by nrweir** [comment]
@dphogan, @opee007: this appears to be an issue with `fiona`'s connection to `GDAL`. I'll leave this issue open in case we need to update our Dockerfile to support the build, but in the meantime, I'd recommend trying to chase it down in `fiona`'s issues (or whatever other support they provide).

**Comment by dphogan** [comment]
This issue is now resolved in the "dev" branch.  (The solution was to modify the YAML file to pin GDAL to version 3.0.3)
